// The map's renderer half: terrain mesh, water, foliage, minimap.
// The landform itself — tiles, city sites, hive lairs, lane-node features —
// is generated by `TerrainField` in `terrain.js`, which stays free of three.js
// so `scripts/map-check.mjs` can build and validate every level in Node.
import * as THREE from 'three';
import { TILE, TILE_INFO } from './config.js';
import { TerrainField } from './terrain.js';
import { makeRNG, makeNoise } from './utils.js';

export class GameMap extends TerrainField {
  colorOf(t) {
    if (this.theme && this.theme.palette) {
      const p = this.theme.palette;
      const map = {
        [TILE.GRASS]: p.grass, [TILE.FOREST]: p.forest, [TILE.WATER]: p.water,
        [TILE.MOUNTAIN]: p.mountain, [TILE.SAND]: p.sand, [TILE.PATH]: p.path,
      };
      if (map[t] !== undefined) return map[t];
    }
    return TILE_INFO[t].color;
  }

  // ---------- Rendering ----------

  buildTerrain() {
    const N = this.size;
    const group = new THREE.Group();

    // Terrain: 2 triangles per tile. Cel look: large SMOOTH fields of color —
    // variation is low-frequency noise, never per-tile jitter (no checkering).
    const positions = new Float32Array(N * N * 6 * 3);
    const colors = new Float32Array(N * N * 6 * 3);
    const col = new THREE.Color();
    const varNoise = makeNoise(makeRNG(1234));
    let p = 0;

    for (let z = 0; z < N; z++) {
      for (let x = 0; x < N; x++) {
        const t = this.tiles[this.idx(x, z)];
        col.setHex(this.colorOf(t));
        const v = (varNoise(x * 0.03, z * 0.03, 2) - 0.5) * 0.05;
        col.offsetHSL(0, 0, v);

        const h00 = this.cornerHeight(x, z);
        const h10 = this.cornerHeight(x + 1, z);
        const h01 = this.cornerHeight(x, z + 1);
        const h11 = this.cornerHeight(x + 1, z + 1);

        const verts = [
          [x, h00, z], [x, h01, z + 1], [x + 1, h10, z],
          [x + 1, h10, z], [x, h01, z + 1], [x + 1, h11, z + 1],
        ];
        for (const [vx, vy, vz] of verts) {
          positions[p] = vx; positions[p + 1] = vy; positions[p + 2] = vz;
          colors[p] = col.r; colors[p + 1] = col.g; colors[p + 2] = col.b;
          p += 3;
        }
      }
    }

    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
    geo.setAttribute('color', new THREE.BufferAttribute(colors, 3));
    geo.computeVertexNormals();
    const mat = new THREE.MeshLambertMaterial({ vertexColors: true });
    const terrain = new THREE.Mesh(geo, mat);
    terrain.receiveShadow = true;
    terrain.name = 'terrain';
    group.add(terrain);

    // Water plane above sunken tiles.
    const waterGeo = new THREE.PlaneGeometry(N, N);
    const waterMat = new THREE.MeshLambertMaterial({
      color: this.theme && this.theme.palette ? this.theme.palette.water : 0x3f8fb0,
      transparent: true, opacity: 0.85,
    });
    const water = new THREE.Mesh(waterGeo, waterMat);
    water.rotation.x = -Math.PI / 2;
    water.position.set(N / 2, -0.22, N / 2);
    group.add(water);

    group.add(this._buildRipples());
    group.add(this._buildTrees());
    group.add(this._buildRocks());
    group.add(this._buildOre());
    return group;
  }

  // White foam dashes: a bright ring hugging every shoreline plus sparse
  // open-water ripples — the hand-inked water read from the reference.
  _buildRipples() {
    const N = this.size;
    const rng = makeRNG(555);
    const spots = [];
    for (let z = 1; z < N - 1; z++) {
      for (let x = 1; x < N - 1; x++) {
        if (this.tiles[this.idx(x, z)] !== TILE.WATER) continue;
        const shore = [[1, 0], [-1, 0], [0, 1], [0, -1]].some(([dx, dz]) => {
          const t = this.tiles[this.idx(x + dx, z + dz)];
          return t !== TILE.WATER;
        });
        if (shore) spots.push({ x: x + 0.5, z: z + 0.5, w: 0.55 + rng() * 0.25, r: 0 });
        else if (rng() < 0.055) spots.push({ x: x + rng(), z: z + rng(), w: 0.4 + rng() * 0.4, r: 0 });
      }
    }
    const geo = new THREE.PlaneGeometry(1, 0.1);
    geo.rotateX(-Math.PI / 2);
    const mat = new THREE.MeshBasicMaterial({ color: 0xeaf4f2, transparent: true, opacity: 0.65, depthWrite: false });
    const mesh = new THREE.InstancedMesh(geo, mat, Math.max(1, spots.length));
    const m = new THREE.Matrix4(), q = new THREE.Quaternion(), sc = new THREE.Vector3(), pos = new THREE.Vector3();
    spots.forEach((s, i) => {
      q.identity();
      sc.set(s.w, 1, 1);
      pos.set(s.x, -0.16, s.z);
      m.compose(pos, q, sc);
      mesh.setMatrixAt(i, m);
    });
    mesh.count = spots.length;
    return mesh;
  }

  _scatter(tile, perTile) {
    const spots = [];
    const rng = makeRNG(777);
    for (let z = 0; z < this.size; z++) {
      for (let x = 0; x < this.size; x++) {
        if (this.tiles[this.idx(x, z)] !== tile) continue;
        const n = perTile(rng);
        for (let i = 0; i < n; i++) {
          spots.push({ x: x + 0.15 + rng() * 0.7, z: z + 0.15 + rng() * 0.7, s: 0.75 + rng() * 0.55, r: rng() * Math.PI * 2 });
        }
      }
    }
    return spots;
  }

  _buildTrees() {
    // Storybook pines: chunkier cones, pale trunks, sparser stands.
    const spots = this._scatter(TILE.FOREST, (rng) => (rng() < 0.62 ? 1 : rng() < 0.9 ? 0 : 2));
    const g = new THREE.Group();
    const trunkGeo = new THREE.CylinderGeometry(0.09, 0.13, 0.55, 5);
    const trunkMat = new THREE.MeshLambertMaterial({ color: 0xcbbfa0 });
    const canopyGeo = new THREE.ConeGeometry(0.56, 1.35, 6);
    const canopyMat = new THREE.MeshLambertMaterial({ color: 0xffffff });

    const trunks = new THREE.InstancedMesh(trunkGeo, trunkMat, spots.length);
    const canopies = new THREE.InstancedMesh(canopyGeo, canopyMat, spots.length);
    trunks.castShadow = canopies.castShadow = true;
    const m = new THREE.Matrix4(), q = new THREE.Quaternion(), sc = new THREE.Vector3(), pos = new THREE.Vector3();
    const c = new THREE.Color();
    const rng = makeRNG(31);
    const up = new THREE.Vector3(0, 1, 0);
    for (let i = 0; i < spots.length; i++) {
      const s = spots[i];
      q.setFromAxisAngle(up, s.r);
      sc.set(s.s, s.s, s.s);
      pos.set(s.x, 0.25 * s.s, s.z);
      m.compose(pos, q, sc);
      trunks.setMatrixAt(i, m);
      pos.y = (0.5 + 0.45) * s.s;
      m.compose(pos, q, sc);
      canopies.setMatrixAt(i, m);
      // Canopies key off the map's forest color — one hue family per map.
      c.setHex(this.colorOf(TILE.FOREST));
      c.offsetHSL((rng() - 0.5) * 0.02, 0.04, (rng() - 0.5) * 0.06 - 0.02);
      canopies.setColorAt(i, c);
    }
    g.add(trunks, canopies);
    return g;
  }

  _buildRocks() {
    const spots = this._scatter(TILE.MOUNTAIN, (rng) => (rng() < 0.4 ? 1 : 0));
    const geo = new THREE.DodecahedronGeometry(0.4, 0);
    const mat = new THREE.MeshLambertMaterial({
      color: this.theme && this.theme.palette ? this.theme.palette.mountain : 0xe9e2cd,
    });
    const mesh = new THREE.InstancedMesh(geo, mat, Math.max(1, spots.length));
    mesh.castShadow = true;
    const m = new THREE.Matrix4(), q = new THREE.Quaternion(), sc = new THREE.Vector3(), pos = new THREE.Vector3();
    const up = new THREE.Vector3(0, 1, 0);
    for (let i = 0; i < spots.length; i++) {
      const s = spots[i];
      q.setFromAxisAngle(up, s.r);
      sc.set(s.s, s.s * 0.8, s.s);
      pos.set(s.x, 1.5 + 0.15, s.z);
      m.compose(pos, q, sc);
      mesh.setMatrixAt(i, m);
    }
    mesh.count = spots.length;
    return mesh;
  }

  _buildOre() {
    const g = new THREE.Group();
    for (const [tile, color] of [[TILE.GOLDORE, 0xf3c53d], [TILE.STONEORE, 0xb8ccd8]]) {
      const spots = this._scatter(tile, (rng) => 1 + (rng() < 0.5 ? 1 : 0));
      if (!spots.length) continue;
      const geo = new THREE.OctahedronGeometry(0.16, 0);
      const mat = new THREE.MeshLambertMaterial({ color, emissive: color, emissiveIntensity: 0.25 });
      const mesh = new THREE.InstancedMesh(geo, mat, spots.length);
      mesh.castShadow = true;
      const m = new THREE.Matrix4(), q = new THREE.Quaternion(), sc = new THREE.Vector3(), pos = new THREE.Vector3();
      const up = new THREE.Vector3(0, 1, 0);
      for (let i = 0; i < spots.length; i++) {
        const s = spots[i];
        q.setFromAxisAngle(up, s.r);
        sc.set(s.s, s.s * 1.6, s.s);
        pos.set(s.x, 0.12, s.z);
        m.compose(pos, q, sc);
        mesh.setMatrixAt(i, m);
      }
      g.add(mesh);
    }
    return g;
  }

  // Draw the base terrain onto a canvas for the minimap.
  drawMinimap(canvas) {
    const N = this.size;
    canvas.width = N; canvas.height = N;
    const ctx = canvas.getContext('2d');
    const img = ctx.createImageData(N, N);
    const c = new THREE.Color();
    for (let z = 0; z < N; z++) {
      for (let x = 0; x < N; x++) {
        c.setHex(this.colorOf(this.tiles[this.idx(x, z)]));
        const o = (z * N + x) * 4;
        img.data[o] = c.r * 255; img.data[o + 1] = c.g * 255; img.data[o + 2] = c.b * 255; img.data[o + 3] = 255;
      }
    }
    ctx.putImageData(img, 0, 0);
  }
}
