// The map's renderer half: terrain mesh, water, foliage, minimap.
// The landform itself — tiles, city sites, hive lairs, lane-node features —
// is generated by `TerrainField` in `terrain.js`, which stays free of three.js
// so `scripts/map-check.mjs` can build and validate every level in Node.
import * as THREE from 'three';
import { TILE, TILE_INFO } from './config.js';
import { TerrainField } from './terrain.js';
import { makeRNG, makeNoise } from './utils.js';

export class GameMap extends TerrainField {
  isLava() {
    return this.theme?.liquid === 'lava';
  }

  colorOf(t) {
    if (this.theme && this.theme.palette) {
      const p = this.theme.palette;
      // Streets read as pale graded roadbed, not dark stamps across the city:
      // lift the authored path tone toward the biome's sand tone.
      if (t === TILE.PATH && p.path !== undefined) {
        if (this._pathBlend === undefined) {
          this._pathBlend = new THREE.Color(p.path).lerp(new THREE.Color(p.sand ?? p.grass), 0.45).getHex();
        }
        return this._pathBlend;
      }
      // Impassable crag must never share a color family with walkable ground
      // (the wastes' light mesa tone read as strollable rock): pull it toward
      // dark slate so "can't walk there" is legible from the palette alone.
      if (t === TILE.MOUNTAIN && p.mountain !== undefined) {
        if (this._cragBlend === undefined) {
          this._cragBlend = new THREE.Color(p.mountain).lerp(new THREE.Color(0x4e463f), 0.38).getHex();
        }
        return this._cragBlend;
      }
      const map = {
        [TILE.GRASS]: p.grass, [TILE.FOREST]: p.forest, [TILE.WATER]: p.water,
        [TILE.MOUNTAIN]: p.mountain, [TILE.SAND]: p.sand, [TILE.PATH]: p.path,
      };
      if (map[t] !== undefined) return map[t];
    }
    return TILE_INFO[t].color;
  }

  // ---------- Rendering ----------

  buildTerrain() {
    const N = this.size;
    const group = new THREE.Group();
    this._cornerH = null; // invalidate: recompute against the current tiles

    // Terrain: 2 triangles per tile. Cel look: large SMOOTH fields of color —
    // variation is low-frequency noise, never per-tile jitter (no checkering).
    //
    // Color lives on the CORNERS, not the tiles: each corner averages the four
    // tiles that meet at it, the same way cornerHeight averages their heights.
    // Biome interiors stay one clean field of color, but every boundary —
    // shore, treeline, crag foot, path edge — becomes a one-tile gradient
    // instead of an axis-aligned staircase between two flat hexes.
    const positions = new Float32Array(N * N * 6 * 3);
    const colors = new Float32Array(N * N * 6 * 3);
    const uvs = new Float32Array(N * N * 6 * 2);
    const col = new THREE.Color();
    const scratch = new THREE.Color();
    const blightCol = new THREE.Color(0x3c2547);
    const varNoise = makeNoise(makeRNG(1234));
    // Painterly ground: a second, broader noise drifts hue and saturation in
    // big warm/cool patches (the hand-painted mottling that makes reference
    // ground feel alive), independent of the fine lightness grain.
    const patchNoise = makeNoise(makeRNG(4321));
    let p = 0;

    // Tile adjacency masks for the color pass: moisture creeps out of water,
    // shade pools under treelines, and cliff feet sit in their own shadow.
    // Cheap box scans at build time; corners average the 4 meeting tiles.
    const nearWater = new Float32Array(N * N);
    const nearForest = new Uint8Array(N * N);
    const nearCrag = new Uint8Array(N * N);
    for (let z = 0; z < N; z++) {
      for (let x = 0; x < N; x++) {
        const i = this.idx(x, z);
        let dw = 9;
        for (let dz = -2; dz <= 2; dz++) {
          for (let dx = -2; dx <= 2; dx++) {
            if (!this.inBounds(x + dx, z + dz)) continue;
            const t = this.tiles[this.idx(x + dx, z + dz)];
            const d = Math.max(Math.abs(dx), Math.abs(dz));
            if (t === TILE.WATER) dw = Math.min(dw, d);
            if (t === TILE.FOREST && d <= 1) nearForest[i] = 1;
            if (t === TILE.MOUNTAIN && d <= 1) nearCrag[i] = 1;
          }
        }
        nearWater[i] = dw <= 2 ? 1 - dw / 3 : 0;
      }
    }

    // Corner colors and heights are shared by up to four tiles; cache them
    // once. Heights first, then colors — the color pass reads the finished
    // height grid to shade slopes.
    const cw = N + 1;
    const cornerCol = new Float32Array(cw * cw * 3);
    const cornerH = new Float32Array(cw * cw);
    for (let z = 0; z <= N; z++) {
      for (let x = 0; x <= N; x++) {
        cornerH[z * cw + x] = this.cornerHeight(x, z);
      }
    }
    for (let z = 0; z <= N; z++) {
      for (let x = 0; x <= N; x++) {
        let r = 0, g = 0, b = 0, n = 0;
        let wet = 0, shadeF = 0, shadeC = 0, waterN = 0;
        for (let dz = -1; dz <= 0; dz++) {
          for (let dx = -1; dx <= 0; dx++) {
            const tx = x + dx, tz = z + dz;
            if (!this.inBounds(tx, tz)) continue;
            const ti = this.idx(tx, tz);
            const t = this.tiles[ti];
            col.setHex(this.colorOf(t));
            r += col.r; g += col.g; b += col.b; n++;
            wet += nearWater[ti];
            shadeF += nearForest[ti];
            shadeC += nearCrag[ti];
            if (t === TILE.WATER) waterN++;
          }
        }
        col.setRGB(r / Math.max(1, n), g / Math.max(1, n), b / Math.max(1, n));
        const nn = Math.max(1, n);
        wet /= nn; shadeF /= nn; shadeC /= nn;
        // Sunlit relief, baked in: high ground lifts toward light, hollows and
        // basins sink — so the landform reads even under flat Lambert shading.
        const h = cornerH[z * cw + x];
        const lift = h >= 0 ? Math.min(0.06, h * 0.045) : Math.max(-0.055, h * 0.09);
        const v = (varNoise(x * 0.03, z * 0.03, 2) - 0.5) * 0.05;
        col.offsetHSL(0, 0, v + lift);
        // Painterly patchwork: broad hue/saturation drift so open ground reads
        // as brushwork — warm patches into cool — never a flat fill.
        const patch = patchNoise(x * 0.016, z * 0.016, 2) - 0.5;
        col.offsetHSL(patch * 0.032, patch * 0.16 + 0.03, patch * 0.02);
        if (waterN === 0) {
          // Moisture gradient: ground within a couple tiles of water darkens
          // and saturates — banks read as damp earth, not the same meadow.
          if (wet > 0) {
            scratch.copy(col).offsetHSL(0.01, 0.14, -0.10);
            col.lerp(scratch, wet * 0.8);
          }
          // Under-canopy shade: the ground at a treeline pools dark, so
          // forests sit IN the ground instead of standing on clean grass.
          if (shadeF > 0) col.offsetHSL(0.004, 0.05, -0.045 * shadeF);
          // Cliff-foot shadow: crag boundaries carry their own occlusion.
          if (shadeC > 0) col.offsetHSL(0, 0.02, -0.05 * shadeC);
        } else if (waterN < n) {
          // Shoreline shallows: the drowned rim of the basin glows lighter
          // and greener under the water plane, giving the water visible depth.
          scratch.setHex(this.isLava() ? 0xd8742e : 0x74c8b8);
          col.lerp(scratch, 0.4);
        }
        // Cliff shading: steep faces darken hard, so the crag boundary reads
        // as a wall you cannot walk up, while gentle walkable rolls (small
        // corner-to-corner drops) stay untouched.
        let drop = 0;
        if (x > 0) drop = Math.max(drop, Math.abs(h - cornerH[z * cw + (x - 1)]));
        if (x < N) drop = Math.max(drop, Math.abs(h - cornerH[z * cw + (x + 1)]));
        if (z > 0) drop = Math.max(drop, Math.abs(h - cornerH[(z - 1) * cw + x]));
        if (z < N) drop = Math.max(drop, Math.abs(h - cornerH[(z + 1) * cw + x]));
        const cliff = Math.min(0.42, Math.max(0, drop - 0.32) * 0.5);
        if (cliff > 0) col.multiplyScalar(1 - cliff);
        // Blighted ground around every hive lair: the stain reads from across
        // the map, so a lair is a place, not a prop dropped on clean grass.
        for (const [nx, nz] of this.nestSpots || []) {
          const nd = Math.hypot(x - nx, z - nz);
          if (nd < 5.5) col.lerp(blightCol, (1 - nd / 5.5) * 0.55);
        }
        const o = (z * cw + x) * 3;
        cornerCol[o] = col.r; cornerCol[o + 1] = col.g; cornerCol[o + 2] = col.b;
      }
    }
    // Cache for groundY: units, zombies and effects sample the ground every
    // frame, and the corner grid only changes when the terrain mesh does.
    this._cornerH = cornerH;
    this._cornerW = cw;

    for (let z = 0; z < N; z++) {
      for (let x = 0; x < N; x++) {
        const h00 = cornerH[z * cw + x];
        const h10 = cornerH[z * cw + (x + 1)];
        const h01 = cornerH[(z + 1) * cw + x];
        const h11 = cornerH[(z + 1) * cw + (x + 1)];

        const verts = [
          [x, h00, z], [x, h01, z + 1], [x + 1, h10, z],
          [x + 1, h10, z], [x, h01, z + 1], [x + 1, h11, z + 1],
        ];
        for (const [vx, vy, vz] of verts) {
          positions[p] = vx; positions[p + 1] = vy; positions[p + 2] = vz;
          const o = (vz * cw + vx) * 3;
          colors[p] = cornerCol[o]; colors[p + 1] = cornerCol[o + 1]; colors[p + 2] = cornerCol[o + 2];
          const up = (p / 3) * 2;
          uvs[up] = vx * 0.21; uvs[up + 1] = vz * 0.21; // world-scale grain tiling
          p += 3;
        }
      }
    }

    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
    geo.setAttribute('color', new THREE.BufferAttribute(colors, 3));
    geo.setAttribute('uv', new THREE.BufferAttribute(uvs, 2));
    geo.computeVertexNormals();
    // Ground grain: a generated near-neutral mottle multiplying the painted
    // corner colors, so open ground has soil-and-scrub surface detail instead
    // of reading as one airbrushed fill. Browser-only; headless map tooling
    // never touches the texture path.
    let grainTex = null;
    if (typeof document !== 'undefined') {
      grainTex = new THREE.TextureLoader().load('assets/textures/terrain-grain.png');
      grainTex.wrapS = grainTex.wrapT = THREE.RepeatWrapping;
      grainTex.colorSpace = THREE.SRGBColorSpace;
      grainTex.anisotropy = 4;
    }
    const mat = new THREE.MeshLambertMaterial({ vertexColors: true, map: grainTex });
    const terrain = new THREE.Mesh(geo, mat);
    terrain.receiveShadow = true;
    terrain.name = 'terrain';
    group.add(terrain);

    // Water plane above sunken tiles.
    const waterGeo = new THREE.PlaneGeometry(N, N);
    const waterMat = new THREE.MeshLambertMaterial({
      color: this.theme && this.theme.palette ? this.theme.palette.water : 0x3f8fb0,
      transparent: true, opacity: 0.85,
      ...(this.isLava() ? { emissive: 0x7a1f08, emissiveIntensity: 0.8 } : {}),
    });
    const water = new THREE.Mesh(waterGeo, waterMat);
    water.rotation.x = -Math.PI / 2;
    water.position.set(N / 2, -0.22, N / 2);
    group.add(water);

    group.add(this._buildRipples());
    group.add(this._buildTrees());
    group.add(this._buildRocks());
    group.add(this._buildOre());
    group.add(this._buildDetail());
    if (this.labyrinthLayout) group.add(this._buildLabyrinthLandmarks());
    return group;
  }

  _buildLabyrinthLandmarks() {
    const group = new THREE.Group();
    const stone = new THREE.MeshLambertMaterial({ color: 0x373442 });
    const bone = new THREE.MeshLambertMaterial({ color: 0xb8ad98 });
    const red = new THREE.MeshLambertMaterial({ color: 0x842f35, emissive: 0x4a1018, emissiveIntensity: 0.8 });
    const blue = new THREE.MeshLambertMaterial({ color: 0x527a91, emissive: 0x183b52, emissiveIntensity: 0.7 });
    const addBox = (x, z, sx, sy, sz, mat, y = 0) => {
      const mesh = new THREE.Mesh(new THREE.BoxGeometry(sx, sy, sz), mat);
      mesh.position.set(x, this.groundY(x, z) + sy / 2 + y, z);
      mesh.castShadow = mesh.receiveShadow = true;
      group.add(mesh);
    };
    const addPillar = (x, z, mat = stone, h = 3.6) => {
      const mesh = new THREE.Mesh(new THREE.CylinderGeometry(0.48, 0.65, h, 7), mat);
      mesh.position.set(x, this.groundY(x, z) + h / 2, z);
      mesh.castShadow = true;
      group.add(mesh);
    };
    const rooms = this.labyrinthLayout.rooms;
    const bridge = rooms[2], reliquary = rooms[3], cells = rooms[5];
    const gallery = rooms[6], gate = rooms[7], throne = rooms[8], start = rooms[0];
    // Last Lantern: a tall blue beacon visible from the first junction.
    addPillar(start.x, start.z + 3, stone, 5.5);
    addBox(start.x, start.z + 3, 1.3, 0.35, 1.3, blue, 5.4);
    // Ash Bridge rails and broken pylons frame a narrow defense lane.
    for (const dx of [-10, -5, 0, 5, 10]) for (const dz of [-4.8, 4.8]) addPillar(bridge.x + dx, bridge.z + dz, stone, 2.2);
    // The Reliquary is a ring of red-lit monoliths.
    for (let i = 0; i < 8; i++) {
      const a = i * Math.PI / 4;
      addPillar(reliquary.x + Math.cos(a) * 8, reliquary.z + Math.sin(a) * 8, i % 2 ? red : stone, 3.8);
    }
    // Drowned Cells and Bone Gallery use different repeated silhouettes.
    for (const dx of [-8, 0, 8]) for (const dz of [-6, 6]) addPillar(cells.x + dx, cells.z + dz, blue, 2.8);
    for (const dx of [-11, -6, -1, 4, 9]) for (const dz of [-5, 5]) addPillar(gallery.x + dx, gallery.z + dz, bone, 3.1);
    // Crown Gate: twin towers and a monumental lintel announce the threshold.
    addPillar(gate.x - 6, gate.z - 5, stone, 7);
    addPillar(gate.x + 6, gate.z - 5, stone, 7);
    addBox(gate.x, gate.z - 5, 13, 1.4, 1.4, red, 5.8);
    // Sunless Throne: stepped dais, rear columns, and a black throne block.
    addBox(throne.x, throne.z - 2, 10, 0.7, 7, stone);
    addBox(throne.x, throne.z - 3, 7, 0.8, 5, bone, 0.7);
    addBox(throne.x, throne.z - 4, 3, 4.5, 2.2, red, 1.4);
    for (const dx of [-10, -5, 5, 10]) addPillar(throne.x + dx, throne.z - 7, stone, 6.5);
    // Room seals are visible energy walls. The simulation closes the matching
    // corridor tiles; these meshes make that state readable to the player.
    this.labyrinthDoorMeshes = [];
    const sealMat = new THREE.MeshLambertMaterial({
      color: 0xb93b4b, emissive: 0x8a1728, emissiveIntensity: 1.2,
      transparent: true, opacity: 0.72,
    });
    for (const def of this.labyrinthLayout.encounters || []) {
      const room = rooms[def.room];
      for (const fromIndex of def.from || []) {
        const from = rooms[fromIndex];
        const dx = from.x - room.x, dz = from.z - room.z;
        const d = Math.hypot(dx, dz) || 1, ux = dx / d, uz = dz / d;
        const x = room.x + ux * 9, z = room.z + uz * 9;
        const seal = new THREE.Mesh(new THREE.BoxGeometry(8.5, 3.4, 0.35), sealMat.clone());
        seal.position.set(x, this.groundY(x, z) + 1.7, z);
        seal.rotation.y = Math.atan2(uz, ux) + Math.PI / 2;
        seal.visible = false;
        seal.userData.encounterKey = def.key;
        group.add(seal);
        this.labyrinthDoorMeshes.push(seal);
      }
    }
    return group;
  }

  syncLabyrinthDoors(game) {
    for (const mesh of this.labyrinthDoorMeshes || []) {
      const state = game.labyrinthEncounters?.find((e) => e.key === mesh.userData.encounterKey);
      mesh.visible = state?.status === 'active' || state?.status === 'sealed';
    }
  }

  // White foam dashes: a bright ring hugging every shoreline plus sparse
  // open-water ripples — the hand-inked water read from the reference.
  _buildRipples() {
    const N = this.size;
    const rng = makeRNG(555);
    const spots = [];
    for (let z = 1; z < N - 1; z++) {
      for (let x = 1; x < N - 1; x++) {
        if (this.tiles[this.idx(x, z)] !== TILE.WATER) continue;
        const shore = [[1, 0], [-1, 0], [0, 1], [0, -1]].some(([dx, dz]) => {
          const t = this.tiles[this.idx(x + dx, z + dz)];
          return t !== TILE.WATER;
        });
        if (shore) spots.push({ x: x + 0.5, z: z + 0.5, w: 0.55 + rng() * 0.25, r: 0 });
        else if (rng() < 0.055) spots.push({ x: x + rng(), z: z + rng(), w: 0.4 + rng() * 0.4, r: 0 });
      }
    }
    const geo = new THREE.PlaneGeometry(1, 0.1);
    geo.rotateX(-Math.PI / 2);
    const mat = new THREE.MeshBasicMaterial({ color: 0xeaf4f2, transparent: true, opacity: 0.65, depthWrite: false });
    const mesh = new THREE.InstancedMesh(geo, mat, Math.max(1, spots.length));
    const m = new THREE.Matrix4(), q = new THREE.Quaternion(), sc = new THREE.Vector3(), pos = new THREE.Vector3();
    spots.forEach((s, i) => {
      q.identity();
      sc.set(s.w, 1, 1);
      pos.set(s.x, -0.16, s.z);
      m.compose(pos, q, sc);
      mesh.setMatrixAt(i, m);
    });
    mesh.count = spots.length;
    return mesh;
  }

  _scatter(tile, perTile) {
    const spots = [];
    const rng = makeRNG(777);
    for (let z = 0; z < this.size; z++) {
      for (let x = 0; x < this.size; x++) {
        if (this.tiles[this.idx(x, z)] !== tile) continue;
        const n = perTile(rng);
        for (let i = 0; i < n; i++) {
          spots.push({ x: x + 0.15 + rng() * 0.7, z: z + 0.15 + rng() * 0.7, s: 0.75 + rng() * 0.55, r: rng() * Math.PI * 2 });
        }
      }
    }
    return spots;
  }

  _buildTrees() {
    // Alien deepwood: leaning trunks under lobed, layered canopies — a tall
    // crown cone with an offset understory lobe, so the treeline is a mass of
    // overlapping rounded silhouettes instead of a picket of identical cones.
    // A few trees carry bioluminescent spore pods that burn through the dark.
    const spots = this._scatter(TILE.FOREST, (rng) => (rng() < 0.62 ? 1 : rng() < 0.9 ? 0 : 2));
    const g = new THREE.Group();
    const trunkGeo = new THREE.CylinderGeometry(0.07, 0.14, 0.7, 5);
    const trunkMat = new THREE.MeshLambertMaterial({ color: 0xcbbfa0 });
    const canopyGeo = new THREE.ConeGeometry(0.52, 1.3, 7);
    const canopyMat = new THREE.MeshLambertMaterial({ color: 0xffffff });
    const lobeGeo = new THREE.SphereGeometry(0.42, 7, 5);
    const lobeMat = canopyMat; // same program: instance color does the varying

    const trunks = new THREE.InstancedMesh(trunkGeo, trunkMat, spots.length);
    const canopies = new THREE.InstancedMesh(canopyGeo, canopyMat, spots.length);
    const lobes = new THREE.InstancedMesh(lobeGeo, lobeMat, spots.length);
    trunks.castShadow = canopies.castShadow = true;
    lobes.castShadow = false; // the crown already shadows the stand
    const m = new THREE.Matrix4(), q = new THREE.Quaternion(), sc = new THREE.Vector3(), pos = new THREE.Vector3();
    const eul = new THREE.Euler();
    const c = new THREE.Color();
    const rng = makeRNG(31);
    const spores = [];
    for (let i = 0; i < spots.length; i++) {
      const s = spots[i];
      const leanX = (rng() - 0.5) * 0.16, leanZ = (rng() - 0.5) * 0.16;
      eul.set(leanX, s.r, leanZ);
      q.setFromEuler(eul);
      sc.set(s.s, s.s * (0.9 + rng() * 0.35), s.s);
      const gy = this.groundY(s.x, s.z);
      pos.set(s.x, gy + 0.32 * s.s, s.z);
      m.compose(pos, q, sc);
      trunks.setMatrixAt(i, m);
      pos.set(s.x + leanX * 0.5, gy + (0.62 + 0.55) * s.s * (0.95 + rng() * 0.2), s.z + leanZ * 0.5);
      m.compose(pos, q, sc);
      canopies.setMatrixAt(i, m);
      // Understory lobe: offset to one side and lower, a second rounded mass.
      const la = rng() * Math.PI * 2, lr = 0.28 + rng() * 0.2;
      pos.set(s.x + Math.cos(la) * lr * s.s, gy + (0.55 + rng() * 0.25) * s.s, s.z + Math.sin(la) * lr * s.s);
      sc.set(s.s * (0.8 + rng() * 0.4), s.s * (0.65 + rng() * 0.3), s.s * (0.8 + rng() * 0.4));
      m.compose(pos, q, sc);
      lobes.setMatrixAt(i, m);
      // Canopies key off the map's forest color — one hue family per map
      // (position-aware so a stitched map can vary palette by region).
      c.setHex(this.colorOf(TILE.FOREST, s.x, s.z));
      c.offsetHSL((rng() - 0.5) * 0.02, 0.04, (rng() - 0.5) * 0.06 - 0.02);
      canopies.setColorAt(i, c);
      c.offsetHSL(0.006, 0.06, -0.03); // understory sits in its own shade
      lobes.setColorAt(i, c);
      if (rng() < 0.16) spores.push({ x: s.x + (rng() - 0.5) * 0.5, z: s.z + (rng() - 0.5) * 0.5, y: gy + (0.5 + rng() * 0.5) * s.s, s: 0.5 + rng() * 0.5 });
    }
    g.add(trunks, canopies, lobes);
    // Spore pods: teal pinpricks hanging in the deepwood (the biome's own
    // bioluminescence — the sci-fi answer to ember-lit fantasy forests).
    if (spores.length) {
      const pods = new THREE.InstancedMesh(
        new THREE.OctahedronGeometry(0.07, 0),
        new THREE.MeshLambertMaterial({ color: 0x5fd8c8, emissive: 0x3fb8a8, emissiveIntensity: 0.9 }),
        spores.length,
      );
      q.identity();
      spores.forEach((s, i) => {
        sc.setScalar(s.s);
        pos.set(s.x, s.y, s.z);
        m.compose(pos, q, sc);
        pods.setMatrixAt(i, m);
      });
      g.add(pods);
    }
    return g;
  }

  _buildRocks() {
    // Crag dressing exists to say "you cannot walk here". Jagged rock teeth
    // crowd the RIM — every crag tile that touches walkable ground grows a
    // spike or two, so the boundary reads as a fence of stone — while the
    // interior plateaus get sparser boulders.
    const N = this.size;
    const g = new THREE.Group();
    const rng = makeRNG(888);
    const teeth = [], boulders = [], scree = [];
    for (let z = 0; z < N; z++) {
      for (let x = 0; x < N; x++) {
        if (this.tiles[this.idx(x, z)] !== TILE.MOUNTAIN) {
          // Rubble apron: walkable ground that touches crag catches the
          // rockfall — the cliff foot reads weathered, not laser-cut.
          if (this.isWalkable(x, z)
            && [[1, 0], [-1, 0], [0, 1], [0, -1]].some(([dx, dz]) => this.inBounds(x + dx, z + dz) && this.tiles[this.idx(x + dx, z + dz)] === TILE.MOUNTAIN)
            && rng() < 0.5) {
            const n = 1 + (rng() < 0.4 ? 1 : 0);
            for (let i = 0; i < n; i++) {
              scree.push({ x: x + 0.15 + rng() * 0.7, z: z + 0.15 + rng() * 0.7, s: 0.6 + rng() * 0.9, r: rng() * Math.PI * 2 });
            }
          }
          continue;
        }
        const rim = [[1, 0], [-1, 0], [0, 1], [0, -1]].some(([dx, dz]) =>
          this.isWalkable(x + dx, z + dz));
        if (rim) {
          const n = 1 + (rng() < 0.55 ? 1 : 0);
          for (let i = 0; i < n; i++) {
            teeth.push({
              x: x + 0.2 + rng() * 0.6, z: z + 0.2 + rng() * 0.6,
              s: 0.8 + rng() * 0.8, r: rng() * Math.PI * 2, tilt: (rng() - 0.5) * 0.3,
              shade: 0.72 + rng() * 0.34,
            });
          }
        } else if (rng() < 0.35) {
          boulders.push({ x: x + 0.15 + rng() * 0.7, z: z + 0.15 + rng() * 0.7, s: 0.75 + rng() * 0.55, r: rng() * Math.PI * 2 });
        }
      }
    }
    const cragCol = this.colorOf(TILE.MOUNTAIN);
    const m = new THREE.Matrix4(), q = new THREE.Quaternion(), sc = new THREE.Vector3(), pos = new THREE.Vector3();
    const eul = new THREE.Euler();
    const c = new THREE.Color();
    if (teeth.length) {
      const mesh = new THREE.InstancedMesh(
        new THREE.ConeGeometry(0.4, 1.5, 5),
        new THREE.MeshLambertMaterial({ color: 0xffffff }),
        teeth.length,
      );
      mesh.castShadow = true;
      const toothBase = new THREE.Color(cragCol).multiplyScalar(0.82);
      teeth.forEach((s, i) => {
        eul.set(s.tilt, s.r, s.tilt * 0.7);
        q.setFromEuler(eul);
        sc.set(s.s, s.s * (0.9 + (i % 3) * 0.25), s.s);
        pos.set(s.x, this.groundY(s.x, s.z) + 0.55 * s.s, s.z);
        m.compose(pos, q, sc);
        mesh.setMatrixAt(i, m);
        // Strata: neighbouring teeth vary light-to-dark, so the rim reads as
        // layered rock faces instead of one repeated prop.
        c.copy(toothBase).multiplyScalar(s.shade);
        mesh.setColorAt(i, c);
      });
      g.add(mesh);
    }
    if (scree.length) {
      const mesh = new THREE.InstancedMesh(
        new THREE.DodecahedronGeometry(0.13, 0),
        new THREE.MeshLambertMaterial({ color: new THREE.Color(cragCol).multiplyScalar(0.9).getHex() }),
        scree.length,
      );
      scree.forEach((s, i) => {
        eul.set(0, s.r, 0);
        q.setFromEuler(eul);
        sc.set(s.s, s.s * 0.65, s.s);
        pos.set(s.x, this.groundY(s.x, s.z) + 0.05, s.z);
        m.compose(pos, q, sc);
        mesh.setMatrixAt(i, m);
      });
      g.add(mesh);
    }
    if (boulders.length) {
      const mesh = new THREE.InstancedMesh(
        new THREE.DodecahedronGeometry(0.4, 0),
        new THREE.MeshLambertMaterial({ color: cragCol }),
        boulders.length,
      );
      mesh.castShadow = true;
      boulders.forEach((s, i) => {
        eul.set(0, s.r, 0);
        q.setFromEuler(eul);
        sc.set(s.s, s.s * 0.8, s.s);
        pos.set(s.x, this.groundY(s.x, s.z) + 0.15, s.z);
        m.compose(pos, q, sc);
        mesh.setMatrixAt(i, m);
      });
      g.add(mesh);
    }
    return g;
  }

  _buildOre() {
    const g = new THREE.Group();
    for (const [tile, color] of [[TILE.GOLDORE, 0xf3c53d], [TILE.STONEORE, 0xb8ccd8]]) {
      const spots = this._scatter(tile, (rng) => 1 + (rng() < 0.5 ? 1 : 0));
      if (!spots.length) continue;
      const geo = new THREE.OctahedronGeometry(0.16, 0);
      const mat = new THREE.MeshLambertMaterial({ color, emissive: color, emissiveIntensity: 0.25 });
      const mesh = new THREE.InstancedMesh(geo, mat, spots.length);
      mesh.castShadow = true;
      const m = new THREE.Matrix4(), q = new THREE.Quaternion(), sc = new THREE.Vector3(), pos = new THREE.Vector3();
      const up = new THREE.Vector3(0, 1, 0);
      for (let i = 0; i < spots.length; i++) {
        const s = spots[i];
        q.setFromAxisAngle(up, s.r);
        sc.set(s.s, s.s * 1.6, s.s);
        pos.set(s.x, this.groundY(s.x, s.z) + 0.12, s.z);
        m.compose(pos, q, sc);
        mesh.setMatrixAt(i, m);
      }
      g.add(mesh);
    }
    return g;
  }

  // Set dressing for the open world — the ground the war is actually fought
  // on, which used to be completely bare. Everything is deterministic from the
  // map seed and the tiles, so peers and rebuilds dress the planet identically.
  //
  // Five instanced meshes, one per silhouette:
  //   tufts    — grass blades over open meadow
  //   pebbles  — scree on grass and sand
  //   boulders — rare big stones on open ground, clear of the city sites
  //   slabs    — standing stones: ruin rings on empty ground, monoliths
  //              flanking every named chokepoint, cairns on barrows, cut
  //              blocks at quarries, moot stones at clearings
  //   posts    — weathered timber: ford markers and clearing stakes
  // Named ground now LOOKS like what the HUD calls it.
  _buildDetail() {
    const N = this.size;
    const g = new THREE.Group();
    const rng = makeRNG(((this.seed | 0) * 31 + 7) >>> 0);
    const nearSite = (x, z, r) => this.sites.some((s) => Math.hypot(x - s.x, z - s.z) < r);
    const nearNest = (x, z, r) => (this.nestSpots || []).some(([nx, nz]) => Math.hypot(x - nx, z - nz) < r);
    const stoneHex = this.theme?.palette?.mountain ?? 0xb8b4a6;

    const tufts = [], pebbles = [], boulders = [], slabs = [], posts = [];
    const polyps = [], pustules = [], glyphs = [];
    const col = new THREE.Color();
    const edgeOf = (x, z, tile) => [[1, 0], [-1, 0], [0, 1], [0, -1], [1, 1], [-1, 1], [1, -1], [-1, -1]]
      .some(([dx, dz]) => this.inBounds(x + dx, z + dz) && this.tiles[this.idx(x + dx, z + dz)] === tile);

    // --- broad scatter over open ground ---
    // Density follows a noise field, not a uniform coin-flip: tufts gather in
    // meadow patches, scree gathers where the meadow thins, and stretches of
    // genuinely clean ground survive between them. Uniform scatter reads as
    // static; patchy scatter reads as a place.
    const meadow = makeNoise(makeRNG(((this.seed | 0) * 17 + 3) >>> 0));
    for (let z = 2; z < N - 2; z++) {
      for (let x = 2; x < N - 2; x++) {
        const t = this.tiles[this.idx(x, z)];
        if (t === TILE.GRASS) {
          const m = meadow(x * 0.05, z * 0.05, 2);
          const clump = Math.max(0, m - 0.42) * 2.0;
          const bare = Math.max(0, 0.42 - m) * 1.6;
          const r = rng();
          if (r < 0.3 * clump * clump) {
            tufts.push({ x: x + 0.15 + rng() * 0.7, z: z + 0.15 + rng() * 0.7, s: 0.7 + rng() * 0.7, ry: rng() * Math.PI * 2 });
          } else if (r < 0.3 * clump * clump + 0.06 * bare) {
            pebbles.push({ x: x + rng(), z: z + rng(), s: 0.55 + rng() * 0.8, ry: rng() * Math.PI * 2 });
          } else if (r > 0.9975 && !nearSite(x, z, 24) && !nearNest(x, z, 8)) {
            boulders.push({ x: x + 0.5, z: z + 0.5, s: 0.7 + rng() * 1.1, ry: rng() * Math.PI * 2 });
          }
          // Bioluminescent polyps: clusters of teal spore-lights along water
          // banks and treelines — this planet's own light in the dark places.
          if (rng() < 0.028 && !nearSite(x, z, 12) && (edgeOf(x, z, TILE.WATER) || edgeOf(x, z, TILE.FOREST))) {
            const cn = 2 + Math.floor(rng() * 3);
            for (let i = 0; i < cn; i++) {
              polyps.push({ x: x + 0.2 + rng() * 0.6, z: z + 0.2 + rng() * 0.6, s: 0.5 + rng() * 0.8 });
            }
          }
        } else if (t === TILE.SAND && rng() < 0.04) {
          pebbles.push({ x: x + rng(), z: z + rng(), s: 0.5 + rng() * 0.7, ry: rng() * Math.PI * 2 });
        }
      }
    }

    // --- blight pustules: the stain around every hive lair grows glowing
    // nodules, so infested ground is lit by its own infection ---
    for (const [nx, nz] of this.nestSpots || []) {
      const cn = 7 + Math.floor(rng() * 4);
      for (let i = 0; i < cn; i++) {
        const a = rng() * Math.PI * 2, d = 1.8 + rng() * 3.2;
        const px = nx + Math.cos(a) * d, pz = nz + Math.sin(a) * d;
        if (!this.inBounds(px | 0, pz | 0) || this.tiles[this.idx(px | 0, pz | 0)] === TILE.WATER) continue;
        pustules.push({ x: px, z: pz, s: 0.5 + rng() * 0.9 });
      }
    }

    // --- ruin rings: a handful of old stone circles out on the frontier, so
    // riding through empty country occasionally finds SOMETHING ---
    const ruinCount = 4 + Math.floor(rng() * 3);
    let guard = 0;
    for (let placed = 0; placed < ruinCount && guard++ < 400; ) {
      const x = 10 + rng() * (N - 20), z = 10 + rng() * (N - 20);
      if (!this.isWalkable(x | 0, z | 0) || nearSite(x, z, 26) || nearNest(x, z, 12)) continue;
      const stones = 4 + Math.floor(rng() * 3);
      const radius = 1.4 + rng() * 0.9;
      for (let i = 0; i < stones; i++) {
        if (rng() < 0.18) continue; // a fallen gap — ruins, not new masonry
        const a = (i / stones) * Math.PI * 2 + rng() * 0.3;
        slabs.push({
          x: x + Math.cos(a) * radius, z: z + Math.sin(a) * radius,
          sx: 0.34, sy: 0.9 + rng() * 0.7, sz: 0.26,
          ry: a + rng() * 0.4, tilt: (rng() - 0.5) * 0.22, weather: 0.75 + rng() * 0.2,
        });
      }
      placed++;
    }

    // --- every named chokepoint gets its pair of monoliths, so "The Neck" is
    // findable on the ground and not only on the HUD ---
    for (const c of this.chokeSpots || []) {
      const t0 = c.tiles[0], t1 = c.tiles[c.tiles.length - 1];
      for (const [tx, tz] of [t0, t1]) {
        const ry = c.axis === 'x' ? 0 : Math.PI / 2;
        const sy = 1.6 + rng() * 0.5;
        slabs.push({
          x: tx + 0.5, z: tz + 0.5,
          sx: 0.5, sy, sz: 0.4,
          ry, tilt: (rng() - 0.5) * 0.14, weather: 0.9,
        });
        // Precursor glyph: a live seam of light on each monolith face — whoever
        // raised these markers wired them to something that still has power.
        glyphs.push({ x: tx + 0.5, z: tz + 0.5, y: sy * 0.55, ry });
      }
    }

    // --- node monuments: each kind of ground worth holding gets a silhouette ---
    for (const n of this.nodeSpots || []) {
      if (n.kind === 'ford') {
        // Crossing markers: two pairs of leaning timber posts.
        for (const [ox, oz] of [[-1.4, -0.8], [1.3, -0.6], [-1.2, 1.0], [1.5, 0.9]]) {
          posts.push({ x: n.x + ox, z: n.z + oz, s: 0.8 + rng() * 0.35, tilt: (rng() - 0.5) * 0.3, ry: rng() * Math.PI });
        }
      } else if (n.kind === 'barrow') {
        // A cairn: three stacked stones, biggest at the bottom.
        for (let i = 0; i < 3; i++) {
          slabs.push({
            x: n.x + (rng() - 0.5) * 0.3, z: n.z + (rng() - 0.5) * 0.3, lift: i * 0.34,
            sx: 0.9 - i * 0.24, sy: 0.4, sz: 0.8 - i * 0.22,
            ry: rng() * Math.PI, tilt: 0, weather: 0.8,
          });
        }
      } else if (n.kind === 'clearing') {
        // The moot: a ring of low seat-stones.
        for (let i = 0; i < 5; i++) {
          const a = (i / 5) * Math.PI * 2 + 0.5;
          slabs.push({
            x: n.x + Math.cos(a) * 1.5, z: n.z + Math.sin(a) * 1.5,
            sx: 0.5, sy: 0.34, sz: 0.42, ry: a, tilt: 0, weather: 0.85,
          });
        }
      } else if (n.kind === 'quarry') {
        // Cut blocks left mid-haul.
        for (const [ox, oz, s] of [[-1.2, 0.4, 0.7], [0.9, -0.9, 0.55], [1.1, 1.0, 0.45]]) {
          slabs.push({ x: n.x + ox, z: n.z + oz, sx: s, sy: s * 0.8, sz: s * 0.9, ry: rng() * Math.PI, tilt: 0, weather: 1.0 });
        }
      }
      // ore: the glowing crystals are already the monument.
    }

    // --- bake the five instanced meshes ---
    const m = new THREE.Matrix4(), q = new THREE.Quaternion(), sc = new THREE.Vector3(), pos = new THREE.Vector3();
    const eul = new THREE.Euler();
    const bake = (spots, geo, mat, place) => {
      if (!spots.length) return;
      const mesh = new THREE.InstancedMesh(geo, mat, spots.length);
      mesh.castShadow = true;
      spots.forEach((s, i) => { place(s); m.compose(pos, q, sc); mesh.setMatrixAt(i, m); });
      g.add(mesh);
      return mesh;
    };

    // Tufts: a squat 4-sided cone reads as a grass clump in the cel style.
    const tuftMesh = bake(tufts, new THREE.ConeGeometry(0.16, 0.34, 4),
      new THREE.MeshLambertMaterial({ color: 0xffffff }), (s) => {
        eul.set(0, s.ry, 0); q.setFromEuler(eul);
        sc.set(s.s, s.s, s.s);
        pos.set(s.x, this.groundY(s.x, s.z) + 0.15 * s.s, s.z);
      });
    if (tuftMesh) {
      const base = new THREE.Color(this.colorOf(TILE.GRASS));
      tufts.forEach((s, i) => {
        col.copy(base).offsetHSL(0, 0.06, 0.03 + (((i * 2654435761) >>> 16 & 255) / 255 - 0.5) * 0.07);
        tuftMesh.setColorAt(i, col);
      });
      tuftMesh.castShadow = false; // thousands of blades: not worth the shadow pass
    }

    bake(pebbles, new THREE.DodecahedronGeometry(0.09, 0),
      new THREE.MeshLambertMaterial({ color: stoneHex }), (s) => {
        eul.set(0, s.ry, 0); q.setFromEuler(eul);
        sc.set(s.s, s.s * 0.7, s.s);
        pos.set(s.x, this.groundY(s.x, s.z) + 0.04, s.z);
      });

    bake(boulders, new THREE.DodecahedronGeometry(0.5, 0),
      new THREE.MeshLambertMaterial({ color: stoneHex }), (s) => {
        eul.set(0, s.ry, 0); q.setFromEuler(eul);
        sc.set(s.s, s.s * 0.75, s.s);
        pos.set(s.x, this.groundY(s.x, s.z) + 0.2 * s.s, s.z);
      });

    const slabMesh = bake(slabs, new THREE.BoxGeometry(1, 1, 1),
      new THREE.MeshLambertMaterial({ color: 0xffffff }), (s) => {
        eul.set(s.tilt || 0, s.ry, 0); q.setFromEuler(eul);
        sc.set(s.sx, s.sy, s.sz);
        pos.set(s.x, this.groundY(s.x, s.z) + s.sy / 2 + (s.lift || 0), s.z);
      });
    if (slabMesh) {
      const stone = new THREE.Color(stoneHex);
      slabs.forEach((s, i) => { col.copy(stone).multiplyScalar(s.weather || 1); slabMesh.setColorAt(i, col); });
    }

    bake(posts, new THREE.CylinderGeometry(0.07, 0.1, 1.0, 5),
      new THREE.MeshLambertMaterial({ color: 0x6b5a44 }), (s) => {
        eul.set(s.tilt || 0, s.ry, (s.tilt || 0) * 0.6); q.setFromEuler(eul);
        sc.set(s.s, s.s, s.s);
        pos.set(s.x, this.groundY(s.x, s.z) + 0.45 * s.s, s.z);
      });

    // --- the glow layer: saturated light accents in the dark places ---
    const polypMesh = bake(polyps, new THREE.SphereGeometry(0.09, 7, 5),
      new THREE.MeshLambertMaterial({ color: 0x5fd8c8, emissive: 0x2fa898, emissiveIntensity: 0.9 }), (s) => {
        q.identity();
        sc.set(s.s, s.s * 1.3, s.s);
        pos.set(s.x, this.groundY(s.x, s.z) + 0.08 * s.s, s.z);
      });
    if (polypMesh) polypMesh.castShadow = false;

    const pustuleMesh = bake(pustules, new THREE.SphereGeometry(0.11, 7, 5),
      new THREE.MeshLambertMaterial({ color: 0x9a4dd8, emissive: 0x7a2db8, emissiveIntensity: 1.1 }), (s) => {
        q.identity();
        sc.set(s.s, s.s * 0.6, s.s);
        pos.set(s.x, this.groundY(s.x, s.z) + 0.05 * s.s, s.z);
      });
    if (pustuleMesh) pustuleMesh.castShadow = false;

    const glyphMesh = bake(glyphs, new THREE.BoxGeometry(0.1, 0.7, 0.44),
      new THREE.MeshBasicMaterial({ color: 0x7fe8d8 }), (s) => {
        eul.set(0, s.ry, 0); q.setFromEuler(eul);
        sc.set(1, 1, 1);
        pos.set(s.x, this.groundY(s.x, s.z) + s.y, s.z);
      });
    if (glyphMesh) glyphMesh.castShadow = false;

    return g;
  }

  // Draw the base terrain onto a canvas for the minimap.
  drawMinimap(canvas) {
    const N = this.size;
    canvas.width = N; canvas.height = N;
    const ctx = canvas.getContext('2d');
    const img = ctx.createImageData(N, N);
    const c = new THREE.Color();
    for (let z = 0; z < N; z++) {
      for (let x = 0; x < N; x++) {
        c.setHex(this.colorOf(this.tiles[this.idx(x, z)]));
        const o = (z * N + x) * 4;
        img.data[o] = c.r * 255; img.data[o + 1] = c.g * 255; img.data[o + 2] = c.b * 255; img.data[o + 3] = 255;
      }
    }
    ctx.putImageData(img, 0, 0);
  }
}
