-- Persistent multiplayer living world. Clients render projections; the service role submits commands.
begin;
create table public.world_shards(id text primary key,name text not null,status text not null default 'active' check(status in('active','paused','archived')),simulation_tick bigint not null default 0 check(simulation_tick>=0),seed bigint not null,ruleset_version integer not null default 1,revision bigint not null default 1,updated_at timestamptz not null default now());
create table public.world_provinces(id uuid primary key default gen_random_uuid(),shard_id text not null references public.world_shards(id) on delete cascade,key text not null,name text not null,bounds jsonb not null,owner_faction_id text,revision bigint not null default 1,unique(shard_id,key));
create table public.world_locations(id uuid primary key default gen_random_uuid(),province_id uuid not null references public.world_provinces(id) on delete cascade,key text not null,name text not null,kind text not null check(kind in('town','fort','village','port','ruin','gate')),position jsonb not null,owner_faction_id text,services jsonb not null default '{}',revision bigint not null default 1,unique(province_id,key));
create table public.world_routes(id uuid primary key default gen_random_uuid(),province_id uuid not null references public.world_provinces(id) on delete cascade,origin_id uuid not null references public.world_locations(id),destination_id uuid not null references public.world_locations(id),distance numeric(12,3) not null check(distance>0),terrain jsonb not null default '{}',danger numeric(5,4) not null default 0 check(danger between 0 and 1),revision bigint not null default 1,check(origin_id<>destination_id),unique(province_id,origin_id,destination_id));
create table public.world_parties(id uuid primary key default gen_random_uuid(),shard_id text not null references public.world_shards(id) on delete cascade,owner_user_id uuid references auth.users(id) on delete set null,owner_faction_id text,leader_character_id uuid references public.game_characters(id) on delete set null,name text not null,kind text not null check(kind in('player','ai','caravan','patrol','garrison')),location_id uuid references public.world_locations(id),route_id uuid references public.world_routes(id),route_progress numeric(8,7) not null default 0 check(route_progress between 0 and 1),speed numeric(10,3) not null default 1 check(speed>0),morale numeric(6,3) not null default 50 check(morale between 0 and 100),fatigue numeric(6,3) not null default 0 check(fatigue between 0 and 100),stance text not null default 'neutral' check(stance in('neutral','hostile','friendly','fleeing','engaged')),revision bigint not null default 1,updated_at timestamptz not null default now(),check((location_id is not null and route_id is null)or(location_id is null and route_id is not null)));
create table public.world_armies(id uuid primary key default gen_random_uuid(),party_id uuid not null unique references public.world_parties(id) on delete cascade,commander_user_id uuid references auth.users(id) on delete set null,combat_power numeric(16,3) not null default 0 check(combat_power>=0),formation jsonb not null default '{}',revision bigint not null default 1);
create table public.world_unit_stacks(id uuid primary key default gen_random_uuid(),army_id uuid not null references public.world_armies(id) on delete cascade,unit_key text not null,tier smallint not null check(tier between 1 and 10),healthy integer not null default 0 check(healthy>=0),wounded integer not null default 0 check(wounded>=0),experience bigint not null default 0 check(experience>=0),revision bigint not null default 1,unique(army_id,unit_key,tier));
create table public.world_cargo(party_id uuid not null references public.world_parties(id) on delete cascade,commodity_key text not null,quantity numeric(16,3) not null check(quantity>=0),reserved_quantity numeric(16,3) not null default 0 check(reserved_quantity>=0 and reserved_quantity<=quantity),revision bigint not null default 1,primary key(party_id,commodity_key));
create table public.world_supplies(party_id uuid not null references public.world_parties(id) on delete cascade,supply_key text not null,quantity numeric(16,3) not null check(quantity>=0),consumption_per_tick numeric(14,6) not null default 0 check(consumption_per_tick>=0),revision bigint not null default 1,primary key(party_id,supply_key));
create table public.world_markets(location_id uuid not null references public.world_locations(id) on delete cascade,commodity_key text not null,stock numeric(16,3) not null check(stock>=0),base_price bigint not null check(base_price>=0),buy_price bigint not null check(buy_price>=0),sell_price bigint not null check(sell_price>=0),revision bigint not null default 1,primary key(location_id,commodity_key));
create table public.world_movement_orders(id uuid primary key default gen_random_uuid(),party_id uuid not null references public.world_parties(id) on delete cascade,route_id uuid not null references public.world_routes(id),issued_by uuid references auth.users(id) on delete set null,issued_tick bigint not null,start_tick bigint not null,expected_arrival_tick bigint not null check(expected_arrival_tick>=start_tick),status text not null default 'queued' check(status in('queued','moving','arrived','cancelled','interrupted')),revision bigint not null default 1);
create unique index world_movement_one_active on public.world_movement_orders(party_id) where status in('queued','moving');
create table public.world_scouting_reports(id uuid primary key default gen_random_uuid(),shard_id text not null references public.world_shards(id) on delete cascade,observer_party_id uuid not null references public.world_parties(id) on delete cascade,subject_party_id uuid references public.world_parties(id) on delete cascade,location_id uuid references public.world_locations(id),observed_tick bigint not null,expires_tick bigint not null check(expires_tick>=observed_tick),accuracy numeric(5,4) not null check(accuracy between 0 and 1),intelligence jsonb not null);
create table public.world_pursuits(id uuid primary key default gen_random_uuid(),shard_id text not null references public.world_shards(id) on delete cascade,pursuer_party_id uuid not null references public.world_parties(id),target_party_id uuid not null references public.world_parties(id),started_tick bigint not null,resolved_tick bigint,state text not null default 'active' check(state in('active','caught','escaped','abandoned')),seed bigint not null,result jsonb,revision bigint not null default 1,check(pursuer_party_id<>target_party_id));
create table public.world_encounters(id uuid primary key default gen_random_uuid(),shard_id text not null references public.world_shards(id) on delete cascade,attacker_party_id uuid not null references public.world_parties(id),defender_party_id uuid not null references public.world_parties(id),created_tick bigint not null,state text not null default 'choosing' check(state in('choosing','negotiating','battle','escaped','surrendered','resolved')),attacker_choice text,defender_choice text,terrain jsonb not null,scouting_snapshot jsonb not null,revision bigint not null default 1,check(attacker_party_id<>defender_party_id));
create table public.world_engagements(id uuid primary key default gen_random_uuid(),encounter_id uuid not null unique references public.world_encounters(id) on delete cascade,seed bigint not null,mode text not null check(mode in('autosim','live_command','hybrid')),state text not null default 'active' check(state in('active','retreat','complete','cancelled')),current_round integer not null default 0,started_tick bigint not null,completed_tick bigint,revision bigint not null default 1);
create table public.world_battle_rounds(engagement_id uuid not null references public.world_engagements(id) on delete cascade,round integer not null check(round>0),attacker_order jsonb not null default '{}',defender_order jsonb not null default '{}',rng_cursor bigint not null,result jsonb not null,state_hash text not null,resolved_at timestamptz not null default now(),primary key(engagement_id,round));
create table public.world_battle_results(engagement_id uuid primary key references public.world_engagements(id) on delete cascade,winner_party_id uuid references public.world_parties(id),outcome text not null check(outcome in('attacker_victory','defender_victory','retreat','surrender','draw')),casualties jsonb not null,prisoners jsonb not null default '{}',cargo_transfers jsonb not null default '{}',retreat_routes jsonb not null default '{}',state_hash text not null,committed_tick bigint not null);
create table public.world_commands(shard_id text not null references public.world_shards(id) on delete cascade,actor_user_id uuid not null references auth.users(id) on delete cascade,request_id text not null check(length(request_id) between 1 and 96),command_type text not null,party_id uuid references public.world_parties(id),expected_revision bigint not null check(expected_revision>0),payload jsonb not null,response jsonb,created_at timestamptz not null default now(),completed_at timestamptz,primary key(shard_id,actor_user_id,request_id));
create table public.world_events(shard_id text not null references public.world_shards(id) on delete cascade,sequence bigint not null,event_id uuid not null default gen_random_uuid(),tick bigint not null,event_type text not null,actor_user_id uuid references auth.users(id) on delete set null,aggregate_type text not null,aggregate_id text not null,aggregate_revision bigint not null,payload jsonb not null,command_request_id text,created_at timestamptz not null default now(),primary key(shard_id,sequence),unique(event_id));
create index world_parties_shard_location on public.world_parties(shard_id,location_id); create index world_events_aggregate on public.world_events(shard_id,aggregate_type,aggregate_id,sequence);
do $$ declare t text; begin foreach t in array array['world_shards','world_provinces','world_locations','world_routes','world_parties','world_armies','world_unit_stacks','world_cargo','world_supplies','world_markets','world_movement_orders','world_scouting_reports','world_pursuits','world_encounters','world_engagements','world_battle_rounds','world_battle_results','world_commands','world_events'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy world_party_owner_read on public.world_parties for select to authenticated using(owner_user_id=auth.uid()); create policy world_army_commander_read on public.world_armies for select to authenticated using(commander_user_id=auth.uid()); create policy world_commands_actor_read on public.world_commands for select to authenticated using(actor_user_id=auth.uid());
create or replace function public.living_world_command(
  p_actor uuid,p_shard text,p_request_id text,p_type text,p_party uuid,p_expected_revision bigint,p_payload jsonb
) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_existing public.world_commands%rowtype; v_party public.world_parties%rowtype;
  v_result jsonb; v_sequence bigint; v_tick bigint;
begin
  if coalesce(auth.role(),'')<>'service_role' then raise exception 'service_role_required'; end if;
  if p_actor is null or p_shard is null or p_request_id is null or length(p_request_id) not between 1 and 96 then raise exception 'invalid_request'; end if;
  if p_type not in('issue_movement','cancel_movement','set_encounter_choice','submit_battle_order','accept_surrender','trade_market') then raise exception 'unsupported_command'; end if;
  if p_payload is null or jsonb_typeof(p_payload)<>'object' then raise exception 'invalid_payload'; end if;

  -- Lock order is shard, then command key, then aggregate row. The simulation
  -- worker must use this same order before it changes a shard or party.
  perform pg_advisory_xact_lock(hashtextextended('world-shard:'||p_shard,0));
  select simulation_tick into v_tick from public.world_shards where id=p_shard for update;
  if not found then raise exception 'shard_not_found'; end if;
  perform pg_advisory_xact_lock(hashtextextended('world-command:'||p_shard||':'||p_actor::text||':'||p_request_id,0));

  select * into v_existing from public.world_commands where shard_id=p_shard and actor_user_id=p_actor and request_id=p_request_id;
  if found then
    if v_existing.command_type<>p_type or v_existing.party_id is distinct from p_party
      or v_existing.expected_revision<>p_expected_revision or v_existing.payload<>p_payload then raise exception 'idempotency_conflict'; end if;
    if v_existing.response is null then raise exception 'request_in_progress'; end if;
    return v_existing.response||jsonb_build_object('duplicate',true);
  end if;

  select * into v_party from public.world_parties where id=p_party and shard_id=p_shard for update;
  if not found then raise exception 'party_not_found'; end if;
  if v_party.owner_user_id is distinct from p_actor then raise exception 'unauthorized_ownership'; end if;
  if v_party.revision<>p_expected_revision then raise exception 'stale_revision'; end if;

  insert into public.world_commands(shard_id,actor_user_id,request_id,command_type,party_id,expected_revision,payload,response,created_at,completed_at)
    values(p_shard,p_actor,p_request_id,p_type,p_party,p_expected_revision,p_payload,null,now(),null);
  -- The shard lock serializes sequence allocation with every command/worker.
  select coalesce(max(sequence),0)+1 into v_sequence from public.world_events where shard_id=p_shard;
  update public.world_parties set revision=revision+1,updated_at=now() where id=p_party returning * into v_party;
  insert into public.world_events(shard_id,sequence,tick,event_type,actor_user_id,aggregate_type,aggregate_id,aggregate_revision,payload,command_request_id)
    values(p_shard,v_sequence,v_tick,'command.accepted',p_actor,'party',p_party::text,v_party.revision,jsonb_build_object('type',p_type,'payload',p_payload),p_request_id);
  v_result:=jsonb_build_object('ok',true,'duplicate',false,'sequence',v_sequence,'partyRevision',v_party.revision);
  update public.world_commands set response=v_result,completed_at=now() where shard_id=p_shard and actor_user_id=p_actor and request_id=p_request_id;
  return v_result;
end $$;
revoke all on function public.living_world_command(uuid,text,text,text,uuid,bigint,jsonb) from public,anon,authenticated; grant execute on function public.living_world_command(uuid,text,text,text,uuid,bigint,jsonb) to service_role;
commit;
